### ISSUE TITLE
не регистрирует новые аккаунты

### ISSUE THREAD

**Issue by unkby** [GravelFire/LostDogsBot#2]
![2024-08-18_23-20-07](https://github.com/user-attachments/assets/54940ba6-418a-4495-babd-78b081fa8241)

**Comment by GravelFire** [comment]
Сейчас исправлю, спасибо что написали <3
Следите за обновлениями и спасибо, что откликнулись, а то я в обновлениях писал, что сам увы не могу проверить =(
